#!/bin/sh

cmd() {
    echo "\$ $@"
    $@
}

version=`opam --version | cut -b 1`

# Avoids network failures when too much jobs are requesting the same archive
# e.g. github spam detection
export OPAMDOWNLOADJOBS=1

if [ $version -eq 1 ]; then
    cmd opam depext -uvy $1
    if ! opam install $1 --dry-run; then
        echo Package unavailable, skipping.
        exit 0
    fi
    cmd opam remote
    cmd opam list
    cmd exec opam depext -uivyj 72 $1
elif [ $version -eq 2 ]; then
    cmd opam remote
    cmd opam list
    export OPAMERRLOGLEN=0
    export OPAMPRECISETRACKING=1
    cmd opam remove -y $1
    cmd opam depext -uivyj 72 $1
    exitcode=$?
    if [ $exitcode -ne 0 ] && [ $exitcode -ne 20 ]; then
        exit $exitcode
    fi
else
    echo "Internal error: contact the maintainer of opam-ci-scripts"
    exit 1
fi
