#!/bin/sh

cmd() {
    echo "\$ $@"
    $@
}

version=`opam --version | cut -b 1`

if [ $version -eq 1 ]; then
    if ! opam install $1 --dry-run; then
        echo Package unavailable, skipping.
        exit 0
    fi
    cmd opam remote
    cmd opam list
    cmd exec opam depext -uivyj 2 $1
elif [ $version -eq 2 ]; then
    cmd opam remote
    cmd opam list
    cmd opam depext -u $1 || exit 1
    export OPAMERRLOGLEN=0
    cmd opam install -yj2 $1
    exitcode=$?
    if [ $exitcode -ne 0 ] && [ $exitcode -ne 20 ]; then
        exit $exitcode
    fi
else
    echo "Internal error: contact the maintainer of opam-ci-scripts"
    exit 1
fi
